---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: readarr
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-driver-nfs
    - name: external-secrets-stores
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/downloads/readarr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
