apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZCa7LfD/gdZHZdG9ipXQXYP25ul47y9UTzcwQHmHoodBElUu,iv:SzJ9LKbK2M1nOIEQIzqgCxsn+ftxdLBGpWjM612/Ofo=,tag:Nj2HVNvN5PyPMke7lqec3g==,type:str]
    credentials.json: ENC[AES256_GCM,data:uoeJS9Pmuj3P89YD51is16JQQmyH63bRJ5RwCLphopvp7Yd8E25cx2iZA1a8BySYckbjdBXVcG6UejDKgObJiPfN3hbAD2xl2o75riCPktL5Of8mL5D7crCTvxxltaHYUkGTZSEkB2RuPppf4GrG8gkrvKIulKE8EnknZM3YU4E/nscUlxYQOjQq16XllxZmYewcWsgH+qzU6EeqzBMVD8zXmJXljIWZy4PEVwJ1KA==,iv:+KG/16/SkOj2o6DfVRq9HVtEW1ve6tywIyNhlTClcMM=,tag:vEF2Sv7b8N1M5IEAfO8EmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mer2rvkzmycr6wxu3dcmwxgwr2hlmukc63zzpdfrd374a96tgq8s9ne6v0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOXFpT3IvSkNuZitiTVhB
            akVtaDNBR0V1TnlWV1pVK1JsYlkxVWwyNlF3CnlUNEI5d0FQTjNtUUhabnNXcXQz
            bENRWmpmckYxNnpwVWRDYXExTzJpRmcKLS0tIHVhRkNFN3BiUS81bDRDSjBINk52
            bHBIbEJhLzF6ZnN6K3AyMkVxTlZmYzAKVwLE7AuXIhqiILU4V2Jenw2QWHO3CWag
            VwB4LIX7FkDVtFdB4NnkoldO6uhvYSQXzhnpiK2ZksolclORnI9yZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T21:50:41Z"
    mac: ENC[AES256_GCM,data:vB+Ym58VGycGaKzakHI1FCEFpTPT+Lsl0mLZ7ieTUA2U7TiVF680xXHBaE2CKwXh2FbYj8PrTUAc+m5oAgMAetU2A1rr3005ArZWmmFnA9H/y6LuK3DoLOrrCq7lqr48rTdYILRYtdDik+SdDO2y/DlUzfafFzteSXdCgTEf0TU=,iv:/V0TNZawc/qRaZU29IcYuqBmlus3sf/OxlebY5Y7mak=,tag:B3VYnYrTKIOBcC9Ujg0HuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
