apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gmyyic9g0JgKcMx9oECMnz5q7MnJ5digz7C6cIPsPexUV7IO,iv:kThhEl0wwqOqsjXa65osmmFDKrtuhP78twhwGGidNII=,tag:cLC95MD7dk1c8f953sd37g==,type:str]
    credentials.json: ENC[AES256_GCM,data:5xQUuB6ZchWI/lK11NBTElAKIy3U7i+YKqO7XR+NxMxagZn2mJ0VzWKFJV+Mpon3Wft2VmW/lCv8FHOFRLgoIUusfBl8xCrGp2o7iBQzKPPwNzIfG3cAXCOakBzDPfD0NnLjEp8xmhkvujvI+T6GmckqUOH0k+C1SfhmQJoIDDRtxW1xP/HpELNCnGbdM2EPpdO7MyaMq+7nXzp1vm7cl/KwnC24XzKuFIWAvZ44qg==,iv:vysNyVKiOivb2QQfM0TDeQOaYwjuGitBqkQa+ZFpafM=,tag:5nGzlmF0Xq5nbZahhlptBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mer2rvkzmycr6wxu3dcmwxgwr2hlmukc63zzpdfrd374a96tgq8s9ne6v0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWDZaK3F4bDdvSUZZYzMy
            ZmVtSmJPRnZXY0twazIrOGJVNHNCN2JMTUVZCk5WckZtbklFWStXcWIvR2VYQ3dR
            cnZ2R0JXOTFUZHVCYTcxL2FFZWpCSFUKLS0tIEZ3cnZQalJjMGlUZ0EzM1BVb216
            ZEs1cVFZUDJFdFVLMVZBWjlhemd2MzAKgLtKaQsvTP67UXClx8DNS75/t4f/OKFA
            wEnxzrbxyPwlQoeMHRLjTicIORJYpRJGdCKFhLEwubzrJ1j1c2aHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T15:27:33Z"
    mac: ENC[AES256_GCM,data:D+JRpNa5PT8vX6GEO/crNCJK3zjiWFFKluj6rzerR14DupliTzVdSrB9PS1n4pxRVM0Hiz5ZBaXxQLOYr4YILYy2wNai60VYvlzMuK4IFyi7d+Ef71lcqxIdf2sXden/rv/ls27P8Md3qKunjTZKKosI/7kfAkjM6T5QcLKG/z4=,iv:SgbOI6rQXb2DN++sfUdebXZkjGNUuT7xhVgXlrRfdZc=,tag:KuDiD90L6XUzCIG8ixr/0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
