---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name bazarr-secret
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        BAZARR__API_KEY: "{{ .BAZARR_API_KEY }}"
        BAZARR__POSTGRES_HOST: &dbHost postgres.database.svc.cluster.local
        BAZARR__POSTGRES_PORT: "5432"
        BAZARR__POSTGRES_USER: &dbUser "{{ .BAZARR__POSTGRES_USER }}"
        BAZARR__POSTGRES_PASSWORD: &dbPass "{{ .BAZARR__POSTGRES_PASSWORD }}"
        BAZARR__POSTGRES_MAIN_DB: bazarr_main
        BAZARR__POSTGRES_LOG_DB: bazarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: bazarr_main bazarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pass }}"
  dataFrom:
    - extract:
        key: bazarr
    - extract:
        key: postgres
