---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      bazarr:
        annotations:
          secret.reloader.stakater.com/reload: &secret bazarr-secret
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: bazarr-secret
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1027
            runAsGroup: 1027
            fsGroup: 1027
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/bazarr
              tag: 1.4.2@sha256:7f152a7b8f46707f5feb68a315d8989cb85ed9e8b6868608f80e6f5eb6cc2e8e
            env:
              TZ: "${CONFIG_TIMEZONE}"
            envFrom:
              - secretRef:
                  name: *secret
            resources:
              requests:
                cpu: 10m
                memory: 256M
              limits:
                memory: 1024M
          subcleaner:
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.2.3
            args:
              - --repo=https://github.com/KBlixt/subcleaner
              - --branch=master
              - --wait=86400 # 1 day
              - --root=/add-ons
            resources:
              requests:
                cpu: 10m
                memory: 10M
              limits:
                memory: 128M
    service:
      main:
        controller: bazarr
        ports:
          http:
            port: &port 6767
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: k8s-config
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: glabdownloadsclaim
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
      add-ons:
        type: emptyDir
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: *port
        tls: [hosts: [*host]]
