---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret prowlarr-secret
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: prowlarr-secret
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 50Gi
              storageClass: k8s-config
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1027
            runAsGroup: 1027
            fsGroup: 1027
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              tag: 1.17.2.4511
            env:
              TZ: "${CONFIG_TIMEZONE}"
              PROWLARR__INSTANCE_NAME: ${APP}
              PROWLARR__PORT: &port 80
              PROWLARR__AUTHENTICATION_METHOD: Forms
              PROWLARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              PROWLARR__ANALYTICS_ENABLED: "False"
              PROWLARR__THEME: dark
              COMPlus_EnableDiagnostics: "0"
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: k8s-config
        retain: true
        globalMounts:
          - path: /config
      media:
        existingClaim: glabdownloadsclaim
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
    ingress:
      main:
        enabled: true
        className: internal
        # annotations:
        #   authentik.home.arpa/enabled: "true"
        #   nginx.ingress.kubernetes.io/auth-signin: |-
        #     https://${HOSTNAME}/outpost.goauthentik.io/start?rd=$escaped_request_uri
        #   gethomepage.dev/enabled: "true"
        #   gethomepage.dev/group: Downloads
        #   gethomepage.dev/name: Sonarr
        #   gethomepage.dev/icon: sonarr.svg
        #   gethomepage.dev/widget.type: sonarr
        #   gethomepage.dev/widget.url: http://sonarr.downloads
        #   gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SONARR_TOKEN}}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: *port
        tls: [hosts: [*host]]
