---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recyclarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/downloads/recyclarr/app
  targetNamespace: downloads
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: sonarr
    - name: radarr
    - name: external-secrets-stores
