---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name foundryvtt-secret
  namespace: games
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      engineVersion: v2
      data:
        # App
        FOUNDRY_USERNAME: "{{ .FOUNDRY_USERNAME }}"
        FOUNDRY_PASSWORD: "{{ .FOUNDRY_PASSWORD }}"
        FOUNDRY_ADMIN_KEY: "{{ .FOUNDRY_ADMIN_KEY }}"
        FOUNDRY_LICENSE_KEY: "{{ .FOUNDRY_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: Foundryvtt
