---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundryvtt
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-charts

  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile: { type: RuntimeDefault }

    controllers:
      foundryvtt:
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          app:
            image:
              repository: ghcr.io/felddy/foundryvtt
              tag: 12.320.0

            env:
              TIMEZONE: '${TIMEZONE}'
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: 'true'
              FOUNDRY_TELEMETRY: false
              FOUNDRY_HOSTNAME: &host 'foundry.${DOMAIN_NAME}'
              FOUNDRY_LOCAL_HOSTNAME: *host
              FOUNDRY_MINIFY_STATIC_FILES: 'true'
              FOUNDRY_PROTOCOL: '4'
              FOUNDRY_PROXY_PORT: '443'
              FOUNDRY_PROXY_SSL: 'true'
            envFrom:
              - secretRef:
                  name: foundryvtt-secret

    service:
      app:
        controller: foundryvtt
        ports:
          http:
            port: 30000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host foundry.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: k8s-config
        retain: true
        globalMounts:
          - path: /data
