---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app foundryvtt
  namespace: games
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  driftDetection:
    mode: enabled
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile: { type: RuntimeDefault }

    controllers:
      *app :
        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          *app :
            image:
              repository: ghcr.io/felddy/foundryvtt
              tag: 13.350.0

            env:
              TIMEZONE: '${TIMEZONE}'
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: 'true'
              CONTAINER_URL_FETCH_RETRY: "50"
              # CONTAINER_PRESERVE_CONFIG: 'true' - Commenting this out to see if this is the issue....
              CONTAINER_PRESERVE_OWNER: '/data'
              FOUNDRY_TELEMETRY: false
              FOUNDRY_HOSTNAME: &host "foundry.${SECRET_DOMAIN}"
              FOUNDRY_LOCAL_HOSTNAME: *host
              FOUNDRY_MINIFY_STATIC_FILES: 'true'
              FOUNDRY_PROTOCOL: '4'
              FOUNDRY_PROXY_PORT: '443'
              FOUNDRY_PROXY_SSL: 'true'
              FOUNDRY_COMPRESS_WEBSOCKET: "true"
            envFrom:
              - secretRef:
                  name: foundryvtt-secret

    service:
      *app :
        controller: *app
        # type: LoadBalancer
        # annotations:
        #   io.cilium/lb-ipam-ips: 192.168.1.140
        ports:
          http:
            port: &port 30000

    ingress:
      *app :
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host foundry.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: k8s-config
        size: 50Gi
        retain: true
        globalMounts:
          - path: /data
