---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: foundryvtt
  namespace: flux-system
spec:
  dependsOn:
    - name: external-dns
    - name: external-secrets-stores
  path: ./kubernetes/apps/games/foundryvtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
