apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:C6ZF6Ntwk8B0zD6GwwLc4io=,iv:Mx59I47QEcZ5VEot20n5lKiFmodeCIYNHtmR08FDK1I=,tag:v4XhmyR1GIB0XxMfJUpaCA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IGrB/+p9TZgmheu6vhxy7Wn+SsETzPk=,iv:mseorIbplaxsJJNnnYZKChgOfEkRmtJ33rE0nUqZVVA=,tag:Dyn5GRYQEJ7pxgOXRiJU9g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:OcXhvvEv24MX6xC4JQLUNEg6AaiwH9QUBKL+SasgSjRmuCgn,iv:5EP7lS05qjaxVUH0EH0xJ9NlUR88QgsovDPlMSnasXA=,tag:V4x/ypGfm8setNwJqIGJQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mer2rvkzmycr6wxu3dcmwxgwr2hlmukc63zzpdfrd374a96tgq8s9ne6v0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U0Y3b1oyWVFyZGVhZ003
            bHNWNTRpaTd4YXoxVjVtRUg0NnppK2NiWEM0CmhiRnR5cEF6S1VlYkF1dUo4c2Ex
            K1pBbTREOEtxcGxzdTBtWjl6djhPQW8KLS0tIDB4dmQrNnNzcHNKWHRwc0h3Wm04
            OUpHQ0lva2VoNFpON2phRUVaRXdhTHcKWGik0/NMNiOCPYd2qiLMdzWNSd3GMCGF
            Hz2ccH04Hx5tRMybBKpImPCY10dGZe9u2YLiDW3caQ/i/MoIzQEybA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-22T21:50:41Z"
    mac: ENC[AES256_GCM,data:pFuHtHLGaOgW+qaK7A1fYquxOMin7kVFQ4w2fRQsqxJrHa7E6lvouw9QgQU+jJs/Y0uI+5rKtWemJDK2DTfjAfj5kWvLRARLbs63f5kdlwWCErXWTBkmkboeT+fvo0G8sDI99YGWWA47prRjDAjGHQgfNzQT6Izv3wirKEzONcY=,iv:rIwO4znAwRJYQ1XIn1fqhIjzCb0a2XsaRgGGGH7Taro=,tag:hYKjnCsrIZg7Iem+t90PUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
