---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: homebridge
  namespace: home
spec:
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: homebridge/homebridge
              tag: "latest"
            env:
              TZ: "${TZ}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8581
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 750Mi
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - secretName: homebridge-tls
            hosts:
              - *host
    configMaps:
      config:
        enabled: true
        nameOverride: startup-sh
        data:
          startup.sh: |-
            #!/bin/sh
            npm install --save homebridge-dummy@latest
            npm install --save homebridge-nest@latest
            npm install --save homebridge-ring@latest

    persistence:
      homebridge:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: k8s-config
        size: 3Gi
        retain: true
        globalMounts:
          - path: /config
      startup-sh:
        enabled: true
        type: configMap
        name: homebridge-startup-sh
        globalMounts:
          - path: /homebridge/startup.sh
            subPath: startup.sh
            defaultMode: 493
