---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homebridge
  namespace: homeautomation
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  interval: 30m
  dependsOn:
    - name: intel-device-plugin-gpu
      namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    controllers:
      *app :
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          *app :
            image:
              repository: homebridge/homebridge
              tag: "latest"
            env:
              TZ: "${TZ}"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8581
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 10m
                memory: 100Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 750Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      *app :
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "homebridge.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
              - *host
    configMaps:
      config:
        enabled: true
        nameOverride: startup-sh
        data:
          startup.sh: |-
            #!/bin/sh
            npm install --save homebridge-dummy@latest
            npm install --save homebridge-nest@latest
            npm install --save homebridge-ring@latest

    persistence:
      homebridge-homebridge:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        storageClass: k8s-config
        size: 3Gi
        retain: true
        globalMounts:
          - path: /homebridge
      startup-sh:
        enabled: true
        type: configMap
        name: homebridge-startup-sh
        globalMounts:
          - path: /homebridge/startup.sh
            subPath: startup.sh
