apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:zobnkfVJuaxGYRZHX5RcU7kQak++Lf9a05effPv/5Fk=,iv:KlxkN66rlNCIGF07vyv1rn99njfi/0NS+Zcqezcj+n4=,tag:d4XFD7R8E/qKAjBORtGTxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mer2rvkzmycr6wxu3dcmwxgwr2hlmukc63zzpdfrd374a96tgq8s9ne6v0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QWpINTZkYW5RSzV4cFR4
            RU1ubWVBcmp1TW0xWFpyT2l6T1ExRHBGbVQ4Ck5aS3hJUm1BZTd0YWhKWmdmbkY2
            RDNGaGwvaFZGZDlHaVJxMk03Z1puUmcKLS0tIEtJV3RPbE5wak1RQldyd3hTbXBO
            dnBSd3RUN2VUVHJ0K25UR3VleGR4QUUKongSYfBr1n9YY+7Fz1DLIMU/flyY7vOI
            guD8fFcSrDzjX3ls6+gY89nvV14Znxc7r7zPVj0ERUybOF6g7/lQ7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-23T15:27:33Z"
    mac: ENC[AES256_GCM,data:N1BTJ64VvLYiARxnX8EJE6qxnsZAkGUDDYmDSupPCoo4V25kHKPxDKajetUPdofbak7/kVbsmeZt3ClzHg6AjBSb2HhC6Y6kOPNKL7+ac70VGWAgVQ3RJkwGFQLG4p0C6P9uO464VRDi8vu5ftR7JCzAdHxu2YsYa74wSYt+5v0=,iv:XTc+c885FCrt5F4Ax3nnSxRBIbS+EZq77NZ2cxwoSqs=,tag:6cNBwP1IDlFt9sn6IYeXpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
