---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: downloads
spec:
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      *app :
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: &secret readarr-secret
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: readarr-secret
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 50Gi
              storageClass: k8s-config
              globalMounts:
                - path: /config
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1027
            runAsGroup: 1027
            fsGroup: 1027
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 65536
        containers:
          *app :
            image:
              repository: ghcr.io/onedr0p/readarr-develop
              tag: 0.3.32.2587
            env:
              TZ: America/Denver
              READARR__INSTANCE_NAME: ${APP}
              READARR__PORT: &port 80
              READARR__AUTHENTICATION_METHOD: None
              READARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              RADARR__ANALYTICS_ENABLED: "False"
              COMPlus_EnableDiagnostics: "0"
            envFrom:
              - secretRef:
                  name: *secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      config:
        accessMode: ReadWriteOnce
        size: 50Gi
        storageClass: k8s-config
        retain: true
        globalMounts:
          - path: /config
      media:
        existingClaim: glabdownloadsclaim
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
    ingress:
      *app :
        enabled: true
        className: internal
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: *app
                  port: *port
        tls:
          - hosts:
            - *host
