---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name lidarr-secret
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        LIDARR__API_KEY: "{{ .LIDARR_API_KEY }}"
        LIDARR__POSTGRES_HOST: &dbHost postgres.database.svc.cluster.local
        LIDARR__POSTGRES_PORT: "5432"
        LIDARR__POSTGRES_USER: &dbUser "{{ .LIDARR__POSTGRES_USER }}"
        LIDARR__POSTGRES_PASSWORD: &dbPass "{{ .LIDARR__POSTGRES_PASSWORD }}"
        LIDARR__POSTGRES_MAIN_DB: lidarr_main
        LIDARR__POSTGRES_LOG_DB: lidarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: lidarr_main lidarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .super_pass }}"
  dataFrom:
    - extract:
        key: lidarr
    - extract:
        key: postgres
